import { useState, useEffect, useCallback } from "react";
import { getSocialCaptions, updateSocialCaption, regenerateSocialCaptions, postToFacebookNow, checkFacebookStatus, type SocialCaption, type FacebookStatus } from "@/lib/api";

const SLOT_LABELS: Record<string, string> = {
  morning: "☀️ Morning (7–9am)",
  lunchtime: "🌤 Lunchtime (12–1pm)",
  evening: "🌙 Evening (6–8pm)",
};

const SCORE_COLOR = (score: number) => {
  if (score >= 8) return "bg-green-100 text-green-800";
  if (score >= 5) return "bg-yellow-100 text-yellow-800";
  return "bg-red-100 text-red-800";
};

type Platform = "facebook" | "instagram" | "twitter";

export default function Social() {
  const [captions, setCaptions] = useState<SocialCaption[]>([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);
  const [expandedId, setExpandedId] = useState<number | null>(null);
  const [activePlatform, setActivePlatform] = useState<Record<number, Platform>>({});
  const [editing, setEditing] = useState<Record<number, Partial<SocialCaption>>>({});
  const [saving, setSaving] = useState<Record<number, boolean>>({});
  const [regenerating, setRegenerating] = useState<Record<number, boolean>>({});
  const [posting, setPosting] = useState<Record<number, boolean>>({});
  const [toast, setToast] = useState<{ msg: string; type: "success" | "error" } | null>(null);
  const [fbStatus, setFbStatus] = useState<FacebookStatus | null>(null);

  const showToast = (msg: string, type: "success" | "error" = "success") => {
    setToast({ msg, type });
    setTimeout(() => setToast(null), 3500);
  };

  const load = useCallback(async () => {
    try {
      setLoading(true);
      const data = await getSocialCaptions();
      setCaptions(data);
    } catch {
      setError("Failed to load social captions.");
    } finally {
      setLoading(false);
    }
  }, []);

  useEffect(() => { load(); }, [load]);

  // Check Facebook connection health on every page load
  useEffect(() => {
    checkFacebookStatus().then(setFbStatus).catch(() => setFbStatus({ ok: false, reason: "check_failed" }));
  }, []);

  function getPlatform(captionId: number): Platform {
    return activePlatform[captionId] ?? "facebook";
  }

  function getCaption(cap: SocialCaption): string {
    const edits = editing[cap.id] ?? {};
    const platform = getPlatform(cap.id);
    if (platform === "facebook") return (edits.captionFacebook ?? cap.captionFacebook) ?? "";
    if (platform === "instagram") return (edits.captionInstagram ?? cap.captionInstagram) ?? "";
    return (edits.captionTwitter ?? cap.captionTwitter) ?? "";
  }

  function setCaption(cap: SocialCaption, value: string) {
    const platform = getPlatform(cap.id);
    const field = platform === "facebook" ? "captionFacebook" : platform === "instagram" ? "captionInstagram" : "captionTwitter";
    setEditing(prev => ({ ...prev, [cap.id]: { ...(prev[cap.id] ?? {}), [field]: value } }));
  }

  function hasEdits(captionId: number) {
    return editing[captionId] && Object.keys(editing[captionId]).length > 0;
  }

  async function handleSave(cap: SocialCaption) {
    if (!hasEdits(cap.id)) return;
    setSaving(prev => ({ ...prev, [cap.id]: true }));
    try {
      const updated = await updateSocialCaption(cap.id, editing[cap.id]!);
      setCaptions(prev => prev.map(c => c.id === cap.id ? { ...c, ...updated } : c));
      setEditing(prev => { const n = { ...prev }; delete n[cap.id]; return n; });
      showToast("Captions saved ✓");
    } catch {
      showToast("Failed to save", "error");
    } finally {
      setSaving(prev => ({ ...prev, [cap.id]: false }));
    }
  }

  async function handleRegenerate(cap: SocialCaption) {
    setRegenerating(prev => ({ ...prev, [cap.id]: true }));
    try {
      const updated = await regenerateSocialCaptions(cap.postId);
      setCaptions(prev => prev.map(c => c.id === cap.id ? { ...c, ...updated } : c));
      setEditing(prev => { const n = { ...prev }; delete n[cap.id]; return n; });
      showToast("Captions regenerated by AI ✓");
    } catch {
      showToast("Regeneration failed", "error");
    } finally {
      setRegenerating(prev => ({ ...prev, [cap.id]: false }));
    }
  }

  async function handlePostFacebook(cap: SocialCaption) {
    if (!confirm(`Post "${cap.postTitle}" to Facebook now?`)) return;
    setPosting(prev => ({ ...prev, [cap.id]: true }));
    try {
      await postToFacebookNow(cap.postId);
      setCaptions(prev => prev.map(c => c.id === cap.id ? { ...c, status: "posted" } : c));
      showToast("Posted to Facebook ✓");
    } catch (err: any) {
      showToast(err.message ?? "Posting failed", "error");
    } finally {
      setPosting(prev => ({ ...prev, [cap.id]: false }));
    }
  }

  function copyToClipboard(text: string) {
    navigator.clipboard.writeText(text).then(() => showToast("Copied to clipboard ✓"));
  }

  if (loading) return <div className="p-8 text-muted-foreground">Loading social captions…</div>;
  if (error) return <div className="p-8 text-red-600">{error}</div>;

  return (
    <div className="p-6 max-w-4xl mx-auto">
      {toast && (
        <div className={`fixed top-4 right-4 z-50 px-4 py-3 rounded-lg shadow-lg text-sm font-medium ${
          toast.type === "success" ? "bg-green-600 text-white" : "bg-red-600 text-white"
        }`}>
          {toast.msg}
        </div>
      )}

      {/* Facebook connection status banner */}
      {fbStatus && !fbStatus.ok && (
        <div className="mb-5 px-4 py-3 bg-red-50 border border-red-200 rounded-xl text-sm flex items-start gap-3">
          <span className="text-red-500 text-lg leading-none mt-0.5">⚠️</span>
          <div className="flex-1">
            <p className="font-semibold text-red-800">Facebook connection problem</p>
            <p className="text-red-700 mt-0.5">
              {fbStatus.graphError
                ? `${fbStatus.graphError.message} (code ${fbStatus.graphError.code})`
                : fbStatus.reason === "not_configured"
                  ? "Facebook Page ID or Access Token not configured."
                  : "Token appears invalid or has been revoked."}
            </p>
            <a href="/settings" className="text-red-600 font-medium underline mt-1 inline-block text-xs">
              Go to Settings to update the token →
            </a>
          </div>
        </div>
      )}
      {fbStatus?.ok && (
        <div className="mb-5 flex items-center gap-2">
          <span className="inline-flex items-center gap-1.5 text-xs font-medium text-green-700 bg-green-50 border border-green-200 rounded-full px-3 py-1">
            <span className="w-1.5 h-1.5 rounded-full bg-green-500 inline-block" />
            Facebook connected
            {fbStatus.tokenIdentity?.name && ` — ${fbStatus.tokenIdentity.name}`}
          </span>
        </div>
      )}

      <div className="mb-6">
        <h1 className="text-2xl font-bold text-foreground">Social Media</h1>
        <p className="text-muted-foreground mt-1 text-sm">
          AI-written captions for each published article — ready for Facebook, Instagram, and X.
        </p>
      </div>

      {captions.length === 0 ? (
        <div className="text-center py-16 text-muted-foreground">
          <p className="text-4xl mb-3">📱</p>
          <p className="font-medium">No social captions yet</p>
          <p className="text-sm mt-1">Captions are generated automatically when articles are published.</p>
        </div>
      ) : (
        <div className="space-y-3">
          {captions.map((cap) => {
            const isExpanded = expandedId === cap.id;
            const platform = getPlatform(cap.id);
            const captionText = getCaption(cap);

            return (
              <div key={cap.id} className="border border-border rounded-xl bg-card overflow-hidden">
                {/* Header row */}
                <button
                  className="w-full flex items-center gap-3 px-4 py-3 text-left hover:bg-muted/30 transition-colors"
                  onClick={() => setExpandedId(isExpanded ? null : cap.id)}
                >
                  <div className="flex-1 min-w-0">
                    <div className="flex items-center gap-2 flex-wrap">
                      <span className="font-medium text-sm text-foreground truncate">{cap.postTitle}</span>
                      {cap.status === "posted" && (
                        <span className="text-xs bg-green-100 text-green-700 px-2 py-0.5 rounded-full font-medium flex-shrink-0">✓ Posted</span>
                      )}
                      {!cap.isSocialWorthy && (
                        <span className="text-xs bg-orange-100 text-orange-700 px-2 py-0.5 rounded-full font-medium flex-shrink-0">⚠ Low priority</span>
                      )}
                    </div>
                    <div className="flex items-center gap-3 mt-0.5 text-xs text-muted-foreground">
                      {cap.recommendedSlot && <span>{SLOT_LABELS[cap.recommendedSlot]}</span>}
                      {cap.socialScore != null && (
                        <span className={`px-1.5 py-0.5 rounded font-medium ${SCORE_COLOR(cap.socialScore)}`}>
                          Score {cap.socialScore}/10
                        </span>
                      )}
                      <span>{new Date(cap.generatedAt).toLocaleDateString("en-IE", { day: "numeric", month: "short" })}</span>
                    </div>
                  </div>
                  <span className="text-muted-foreground text-xs">{isExpanded ? "▲" : "▼"}</span>
                </button>

                {/* Expanded content */}
                {isExpanded && (
                  <div className="px-4 pb-4 border-t border-border">
                    {/* Platform tabs */}
                    <div className="flex gap-1 mt-3 mb-3">
                      {(["facebook", "instagram", "twitter"] as Platform[]).map(p => (
                        <button
                          key={p}
                          onClick={() => setActivePlatform(prev => ({ ...prev, [cap.id]: p }))}
                          className={`px-3 py-1.5 rounded-lg text-xs font-medium transition-colors ${
                            platform === p
                              ? "bg-primary text-primary-foreground"
                              : "bg-muted text-muted-foreground hover:bg-muted/80"
                          }`}
                        >
                          {p === "facebook" ? "📘 Facebook" : p === "instagram" ? "📷 Instagram" : "🐦 X / Twitter"}
                        </button>
                      ))}
                    </div>

                    {/* Caption editor */}
                    <div className="relative">
                      <textarea
                        className="w-full border border-border rounded-lg p-3 text-sm bg-background text-foreground resize-none focus:outline-none focus:ring-2 focus:ring-primary/50"
                        rows={platform === "twitter" ? 3 : 5}
                        value={captionText}
                        onChange={e => setCaption(cap, e.target.value)}
                        placeholder={`${platform === "twitter" ? "X / Twitter" : platform === "instagram" ? "Instagram" : "Facebook"} caption…`}
                      />
                      {platform === "twitter" && (
                        <div className={`text-right text-xs mt-0.5 ${captionText.length > 200 ? "text-red-500" : "text-muted-foreground"}`}>
                          {captionText.length}/280
                        </div>
                      )}
                    </div>

                    {/* Hashtags */}
                    {cap.hashtags && (
                      <div className="mt-2 flex items-center gap-2">
                        <span className="text-xs text-muted-foreground">Tags:</span>
                        <span className="text-xs text-blue-600 font-mono">{cap.hashtags}</span>
                      </div>
                    )}

                    {/* Action buttons */}
                    <div className="flex flex-wrap gap-2 mt-4">
                      <button
                        onClick={() => copyToClipboard(captionText + (cap.hashtags ? `\n\n${cap.hashtags}` : ""))}
                        className="px-3 py-1.5 text-xs rounded-lg border border-border bg-background hover:bg-muted transition-colors"
                      >
                        📋 Copy
                      </button>

                      {hasEdits(cap.id) && (
                        <button
                          onClick={() => handleSave(cap)}
                          disabled={saving[cap.id]}
                          className="px-3 py-1.5 text-xs rounded-lg bg-primary text-primary-foreground hover:bg-primary/90 transition-colors disabled:opacity-50"
                        >
                          {saving[cap.id] ? "Saving…" : "💾 Save changes"}
                        </button>
                      )}

                      <button
                        onClick={() => handleRegenerate(cap)}
                        disabled={regenerating[cap.id]}
                        className="px-3 py-1.5 text-xs rounded-lg border border-border bg-background hover:bg-muted transition-colors disabled:opacity-50"
                      >
                        {regenerating[cap.id] ? "Regenerating…" : "✨ Regenerate AI"}
                      </button>

                      {cap.status !== "posted" && (
                        <button
                          onClick={() => handlePostFacebook(cap)}
                          disabled={posting[cap.id]}
                          className="px-3 py-1.5 text-xs rounded-lg bg-blue-600 text-white hover:bg-blue-700 transition-colors disabled:opacity-50"
                        >
                          {posting[cap.id] ? "Posting…" : "📘 Post to Facebook now"}
                        </button>
                      )}

                      <a
                        href={`/article/${cap.postSlug}`}
                        target="_blank"
                        rel="noopener noreferrer"
                        className="px-3 py-1.5 text-xs rounded-lg border border-border bg-background hover:bg-muted transition-colors"
                      >
                        🔗 View article
                      </a>
                    </div>
                  </div>
                )}
              </div>
            );
          })}
        </div>
      )}
    </div>
  );
}
